# Generated by Django 3.1.1 on 2020-10-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantencion',
            options={'ordering': ['-id'], 'verbose_name': 'Mantención', 'verbose_name_plural': 'Mantenciones'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='estado_depto',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Mantencion', 'Mantencion'), ('Nuevo', 'Nuevo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Nueva', 'Nueva'), ('En uso', 'En uso'), ('Anulada', 'Anulada'), ('Finalizada', 'Finalizada')], max_length=100),
        ),
    ]
