# Generated by Django 3.1.2 on 2020-11-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201031_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='image',
            field=models.ImageField(null=True, upload_to='deptos/images/'),
        ),
    ]
