# Generated by Django 3.1.2 on 2020-11-07 21:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201105_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='id_tiposervicioextra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tiposervicioextra'),
        ),
        migrations.CreateModel(
            name='RecibirPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=0, verbose_name='Monto')),
                ('observaciones', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('id_depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.departamento')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.reserva')),
            ],
        ),
    ]
