# Generated by Django 3.1.2 on 2020-11-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201107_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Imagen'),
        ),
    ]
