# Generated by Django 3.1.2 on 2020-11-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201119_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibirpago',
            name='id_depto',
        ),
    ]
