# Generated by Django 3.0.4 on 2020-11-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_recibirpago_id_depto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibirpago',
            options={'ordering': ['-id'], 'verbose_name': 'Recibir Pago', 'verbose_name_plural': 'Recibir Pagos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-id'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_lista',
            field=models.BooleanField(default=False, verbose_name='CheckList Realizado'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_multa',
            field=models.BooleanField(default=False, verbose_name='Cálculo Multa'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_pdf',
            field=models.BooleanField(default=False, verbose_name='Impresión PDF'),
        ),
    ]
