# Generated by Django 3.0.4 on 2020-11-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201120_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['id_reserva'], 'verbose_name': 'CheckIn', 'verbose_name_plural': 'Checks In'},
        ),
        migrations.AlterField(
            model_name='checkin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='id_reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Reserva'),
        ),
    ]
