# Generated by Django 3.0.4 on 2020-11-21 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201120_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='id_reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Reserva'),
        ),
    ]
