# Generated by Django 3.0.4 on 2020-11-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201120_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['id_reserva'], 'verbose_name': 'CheckOut', 'verbose_name_plural': 'Checks Out'},
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='id_depto',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='id_depto',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='id_reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Reserva'),
        ),
    ]
