# Generated by Django 3.0.4 on 2020-11-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20201120_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='id_depto',
        ),
    ]
