# Generated by Django 3.0.4 on 2020-11-21 17:58

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_checklist_id_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='fecha',
            field=models.DateTimeField(default=web.models.get_now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Nueva', 'Nueva'), ('En uso', 'En uso'), ('Anulada', 'Anulada'), ('Reembolsado', 'Reembolsado'), ('Finalizada', 'Finalizada')], max_length=100),
        ),
    ]
