# Generated by Django 3.0.4 on 2020-11-21 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20201121_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
