# Generated by Django 3.0.4 on 2020-11-21 19:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20201121_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='fecha_dia',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='fecha_hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DIA'),
        ),
    ]
