# Generated by Django 3.0.4 on 2020-11-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20201121_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleservicio',
            name='fecha',
        ),
    ]
