# Generated by Django 3.0.4 on 2020-11-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20201121_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibirpago',
            name='id_detalleservicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.DetalleServicio'),
        ),
    ]
