# Generated by Django 3.0.4 on 2020-11-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_recibirpago_id_detalleservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='check_pago',
            field=models.BooleanField(default=False, verbose_name='Completó Pago'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='estado_servicio',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Aceptada', 'Aceptada'), ('Pagado', 'Pagado'), ('Anulada', 'Anulada'), ('Realizado', 'Realizado')], max_length=100),
        ),
    ]
