# Generated by Django 3.0.4 on 2020-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20201122_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='estado_mantencion',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Realizado', 'Realizado')], default='Nueva', max_length=100),
        ),
    ]
